language: php
php:
  - 5.3
  - 5.4
  - hhvm
before_script:
  - mkdir logs
  - chmod 777 logs
  - cp tests/config-test.inc.dist.php tests/config-test.inc.php
  - composer install --dev --prefer-source --no-interaction
  - mysql -e 'create database payutc_test;'
script: ./tests/run_all.sh


